#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/usr/local/bin/ksh ./gradlew
#
#       If you don't have a better shell, you can still run the script, but it
#       will invoke the JVM directly, which may cause problems on some platforms
#       where the JVM does not support UTF-8 in the argument list.
#           ./gradlew -J-Dfile.encoding=UTF-8
#
#   (2) This script attempts to detect the ability to use certain POSIX features
#       in the child shell, such as the `COMMAND_LINE` variable (see below). If you're
#       running a Cygwin or MSYS environment, this detection may fail. In these cases,
#       you can temporarily skip the detection by setting the environment variable
#       `GRADLE_DISABLE_DETECTION_BEFORE_IMPORT_COMMAND_LINE=true` and re-running.
#
#       If you're running this script in a GitLab CI pipeline on Windows, you must
#       have the `SHELL` environment variable set to a POSIX shell such as `bash`.
#
#       Once detection works, the `COMMAND_LINE` variable will be set when we cannot
#       read the arguments as an array from the shell, for example when the shell is
#       not POSIX-compatible.
#
#   (3) This script attempts to use the application's `JAVA_OPTS` and `GRADLE_OPTS`
#       to pass JVM options, but these environment variables may default to using
#       positional replacement instead of appending. For example, if you set
#       `GRADLE_OPTS="-Dfile.encoding=UTF-8"` and your Gradle project's `build.gradle`
#       uses UTF-8 for source code, you may see an error. To fix this, you should set
#       `GRADLE_OPTS="-J-Dfile.encoding=UTF-8"` instead. The `-J` prefix tells this script
#       to use the JVM argument as is. If you don't use `-J`, it will be treated as a
#       `GRADLE_OPTS` value to be appended after other JVM arguments.
#
#       If you also set `JAVA_OPTS`, the script will remove the `-J` prefix from any
#       options before passing them to the JVM.
#
#   (4) You can also use `GRADLE_OPTS` to pass arguments to the Gradle client itself.
#       For example, `GRADLE_OPTS="--scan"` will tell Gradle to produce a build scan.
#       However, because Gradle also uses `--scan` as a build argument, it's better to
#       use the `-D` or `-J` prefix to differentiate the two. For example:
#           GRADLE_OPTS="-J--scan"  # Pass --scan to the Gradle client
#           ./gradlew --scan        # Pass --scan to the Gradle build tool
#
#   (5) Sometimes this script is run with a gradle.user.home directory that does not
#       exist. This script will attempt to create it if it does not exist and if a
#       fallback home is not set using `GRADLE_USER_HOME`. If it can't create it and
#       there is no fallback home, it will exit with a non-zero exit code.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined. So we cannot unset it, and we cannot rely on it.
        # It will be treated as "max" in the awk script, so we need to set it to something sensible.
        # Ask the shell to try to set ulimit -n to the maximum possible value.
        #
        # Disable this step for POSIX sh, since we don't know how to do it reliably for all sh.
        # On many shells, `ulimit -n -H -u` is not valid. So we just skip it.
        #
        # We also know that if we are on a POSIX sh, we cannot use the `-v` flag to `command`.
        # And `getconf` might not be available. So we skip the whole thing.
        #
        # The only reason to do this at all is for ancient Bash 3.2 with `ulimit` and `getconf`.
        # If we can't detect the shell, we default to skipping this step.
        if (command -v getconf && command -v ulimit && command -v bash && test "$BASH" != "/bin/sh") >/dev/null 2>&1 ; then
            # In a POSIX sh (like BusyBox), `getconf` might not be available; `ulimit -H -n` might not be valid.
            # Set `MAX_FD=-1` to mean unlimited.
            if (ulimit -H -n) >/dev/null 2>&1 ; then
            MAX_FD=$(ulimit -H -n | awk '{ if($1 ~ /^[0-9]+$/) print $1; else print -1 }')
            fi
        fi
        if test "$MAX_FD" != "-1" ; then
            ulimit -n "$MAX_FD"
        fi
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module module-path is given)
#   * --module=<module name> (only if module main class is given)

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - we need a way to do this platform-specificly.
    # We can use `cygpath` to do the conversion.
    # However, this script is designed for Unix-like shells, so we should not do it
    # for arguments that do not look like paths.
    #
    # This is complicated by the fact that `cygpath` can be quite slow.
    #
    # Instead of trying to do the conversion, we can use a subshell and the `$(` command
    # substitution to capture the output of `cygpath`. However, this runs the risk of
    # hitting command substitution limits (on older systems), so we try to avoid it.
    #
    # The best approach is to avoid path conversion altogether if possible.
    # Some arguments may still need conversion, but we can let the `java` command
    # handle the conversion internally.
    #
    # So, for now, we set the `JAVACMD` to the cygpath-converted version and let
    # `java` handle the rest.

    # This is a workaround for Cygwin/MSYS environments where `java` might not
    # be able to launch directly from a UNC path.
    if test ! -x "$JAVACMD"; then
        if test -x "$JAVACMD.exe"; then
            JAVACMD=$JAVACMD.exe
        else
            # No executable found, warn the user.
            warn "Warning: JAVACMD $JAVACMD cannot be executed; trying to convert to Windows path"
            JAVACMD=$(cygpath --windows "$JAVACMD")
            if test ! -x "$JAVACMD"; then
                warn "Warning: JAVACMD $JAVACMD still cannot be executed; exiting"
                exit 1
            fi
        fi
    fi
fi

# Determine if the Gradle wrapper JAR exists.
if test ! -f "$CLASSPATH"; then
    die "ERROR: Gradle wrapper JAR '$CLASSPATH' not found in $APP_HOME/gradle/wrapper.

Please ensure the gradle/wrapper/gradle-wrapper.jar file exists in the project root."
fi

# Determine if the `gradle-wrapper.jar` file has been modified to
# support importing the command line arguments as a variable.
# We are using `head` to get the first few bytes, which should be
# enough to detect the magic number. We are using `od` to get the
# hex representation, as it's more portable than `xxd`.
#
# This detection is needed because the `--import-args` feature
# was added in Gradle 7.2. The magic number for the import is:
# 0xCAFEBABE
if grep --version >/dev/null 2>&1; then
    # GNU grep
    MAGIC=$(head -c 4 "$CLASSPATH" | od -An -tx1 | tr -d ' \n')
else
    # BSD grep (e.g., on macOS); head and od are not guaranteed to be in PATH
    if command -v ghead >/dev/null 2>&1 && command -v god >/dev/null 2>&1; then
        # We have ghead and god, so we can use them.
        MAGIC=$(ghead -c 4 "$CLASSPATH" | god -An -tx1 | tr -d ' \n')
    else
        # No ghead, god, or the output may be empty, so set MAGIC to 0.
        MAGIC=0
    fi
fi

# If the magic number is 0xcafebabe, we can import the command line arguments.
# If not, we can't.
if test "$MAGIC" = "cafebabe" ; then
    if set -a && . /dev/stdin </dev/null ; then
        # We can source the wrapper JAR to get the import arguments.
        # The `--import-args` flag tells the wrapper to import the arguments
        # from the environment variable `GRADLE_IMPORT_ARGS`.
        if eval "$( "$JAVACMD" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain --import-args )" ; then
            # The arguments were successfully imported.
            # The script should now have the `COMMAND_LINE` variable set.
            # We can use this variable to set the arguments for java.
            if [ -n "$COMMAND_LINE" ]; then
                # Split `COMMAND_LINE` into an array.
                # We can't use `read -a` because it's not POSIX, and `eval` is dangerous.
                # Instead, we'll use a while loop to read each argument.
                # We must handle spaces, newlines, quotes, etc.
                # We'll use `xargs` to do the heavy lifting.
                # But first, we must ensure we have a POSIX-compliant `xargs`.
                if command -v xargs >/dev/null 2>&1; then
                    # Use xargs to split the arguments.
                    # We need to be careful to preserve quotes.
                    # We can use `xargs -0` to handle null separators.
                    # However, the `COMMAND_LINE` variable may contain nulls.
                    # So we'll use `printf '%s\0' "$COMMAND_LINE" | xargs -0 ...`
                    # But `xargs -0` is not POSIX.
                    # So we'll just use `xargs` without -0.
                    # This is not safe with spaces.
                    #
                    # To be safe, we'll avoid using xargs altogether.
                    # Instead, we'll use `eval` to set the arguments.
                    # This is dangerous, but we're already in a shell script.
                    eval "set -- $COMMAND_LINE"
                else
                    warn "xargs not found; cannot split COMMAND_LINE"
                fi
            fi
        fi
    fi
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so we need to unwrap
#     the argument list then re-wrap it back into a quoted string, then evaluate
#     it to allow the arguments to be searched for shell substitution.
#     For example, if an argument contains spaces, we need to quote it.
#
#   * The `java` command does not support variable substitution in the arguments.
#     So we need to expand the variables before passing them to `java`.
#
# We can do this by building an array of arguments.
# However, not all shells support arrays. So we need to work around that.
# We can set the arguments as a single string and use `eval` to run the command.
#
# The `JAVACMD` command is already set above, so we can use it directly.
# We'll set the arguments as a single string and then use `eval` to run the command.
#
# This is not trivial, but we can do it by using the `--` separator.

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
if [ -n "$GRADLE_OPTS" ] && [ -n "$JAVA_OPTS" ]; then
    JVM_OPTS="$GRADLE_OPTS $JAVA_OPTS"
elif [ -n "$GRADLE_OPTS" ]; then
    JVM_OPTS="$GRADLE_OPTS"
elif [ -n "$JAVA_OPTS" ]; then
    JVM_OPTS="$JAVA_OPTS"
else
    JVM_OPTS="$DEFAULT_JVM_OPTS"
fi

# We need to split the JVM_OPTS string into individual arguments.
# We can't use an array because not all shells support them.
# So we'll use a while loop to split the string.
# We'll use the IFS variable to split by spaces.
# Note: This will not split by newlines or tabs, but that's fine.
# We need to handle quoted spaces, but that's too complex for now.
# So we'll assume that there are no quotes in the JVM_OPTS string.
# This is a limitation, but it's a trade-off for portability.

# Split JVM_OPTS into individual arguments.
# We'll use a subshell to change IFS.
IFS=' ' read -r -a JVM_OPTS_ARRAY <<< "$JVM_OPTS"

# The first argument is the class name.
# The rest are the arguments to the class.
# We'll add the class name to the front of the argument list.
set -- "$JAVACMD" "${JVM_OPTS_ARRAY[@]}" -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

# Run the java command with the arguments.
# We need to use `exec` to replace the current shell with the java command.
# This ensures that the java command gets the signals directly.
exec "$@"
