pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    // Change from FAIL_ON_PROJECT_REPOS to PREFER_PROJECT_REPOS or PREFER_SETTINGS
    // This allows plugins to add their own repositories while still using settings repos
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fabricmc.net/' }
    }
}
rootProject.name = "VulkanUnified"
include ':app'
include ':mod'
