pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    // Use PREFER_PROJECT (not PREFER_PROJECT_REPOS)
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fabricmc.net/' }
    }
}
rootProject.name = "VulkanUnified"
include ':app'
include ':mod'
